name: Code Review
on:
  pull_request:
    types: [opened,synchronize]

jobs:
  message-check:
    name: Block Autosquash Commits

    permissions:
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Block Autosquash Commits
        uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.github_token }}
