name: Docker linter
on:
  pull_request:
    types: [opened,synchronize]
    # paths:
    #   - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hadolint:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: reviewdog/action-hadolint@v1
        with:
          fail_on_error: true
          filter_mode: diff_context
          level: error
          reporter: github-pr-check
