name: GitHub Actions linter
on:
  pull_request:
    types: [opened,synchronize]
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
          filter_mode: diff_context
          level: error
          reporter: github-pr-check
